spring.application.name=myApi
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173
app.cors.allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
app.cors.allowed-headers=Authorization,Content-Type
app.cors.exposed-headers=Authorization
app.cors.allow-credentials=true
